apiVersion: v1
kind: Secret
metadata:
  name: ml-platform-secrets
  namespace: ml-platform
type: Opaque
stringData:
  # Airflow
  AIRFLOW__CORE__FERNET_KEY: "GgyJ5jUehSy2zQqY958eUWW1ezEgNp4OerBy-AKuD14="
  AIRFLOW__WEBSERVER__SECRET_KEY: "mysecretkey-change-in-production"
  AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: "postgresql+psycopg2://airflow:airflow@postgresql/airflow"
  AIRFLOW__CELERY__RESULT_BACKEND: "db+postgresql://airflow:airflow@postgresql/airflow"
  AIRFLOW__CELERY__BROKER_URL: "redis://:redispassword@redis:6379/0"
  _AIRFLOW_WWW_USER_USERNAME: "admin"
  _AIRFLOW_WWW_USER_PASSWORD: "admin123-change-in-production"
  
  # PostgreSQL - Airflow Metadb
  POSTGRES_USER_AIRFLOW: "airflow"
  POSTGRES_PASSWORD_AIRFLOW: "airflow"
  POSTGRES_DB_AIRFLOW: "airflow"
  
  # PostgreSQL - MLflow Backend
  POSTGRES_USER_MLFLOW: "mlflow"
  POSTGRES_PASSWORD_MLFLOW: "mlflow-pwd"
  POSTGRES_DB_MLFLOW: "mlflow-db"
  
  # PostgreSQL - EDF Data
  POSTGRES_USER_EDF: "postgres"
  POSTGRES_PASSWORD_EDF: "postgres"
  POSTGRES_DB_EDF: "postgres"
  
  # Redis
  REDIS_PASSWORD: "redispassword"
  
  # MLflow
  MLFLOW_DB_URI: "postgresql+psycopg2://mlflow:mlflow-pwd@postgresql:5432/mlflow-db"
  
  # S3 Credentials (OVH Object Storage)
  AWS_ACCESS_KEY_ID: "your-s3-access-key"
  AWS_SECRET_ACCESS_KEY: "your-s3-secret-key"
  AWS_DEFAULT_REGION: "gra"
  S3_ENDPOINT_URL: "https://s3.gra.cloud.ovh.net"
  S3_BUCKET_NAME: "ml-platform-storage"
